### ISSUE TITLE
Simplify the Guide

### ISSUE THREAD

**Issue by suslmk-lee** [PaaS-TA/paas-ta-container-platform#1]
### Simplify the Guide
1. standalond Deploy
2. Edge  @Deploy
3. CaaS Deploy

There are many tasks that need to be handled manually, such as downloading images and uploading to the repository.
Simplifying with shell files is     #@@@required.

**Comment by hoon77** [comment]
Simplify deployment by adding scripts
- Replace the value of the env variable in container platform yaml
- Create and Deploy the container platform Resource

Standalone, Edge and Caas Guide has been modified.

**Comment by suslmk-lee** [comment]
Review and close the issue.
