### ISSUE TITLE
Add CVE Action Guide (from ingress)

### ISSUE THREAD

**Issue by suslmk-lee** [PaaS-TA/paas-ta-container-platform#2]
### Add CVE Action Guide (from ingress)

1. X.509 Certificate Subject CN Does Not Match the Entity Name (certificate-common-name-mismatch)
2. Untrusted TLS/SSL server X.509 certificate (tls-untrusted-ca)
3. Self-signed TLS/SSL certificate (ssl-self-signed-certificate)

**Comment by jinyung0101java2** [comment]
Issue content action completed.
