### ISSUE TITLE
xip.io --> nip.io 변경

### ISSUE THREAD

**Issue by suslmk-lee** [PaaS-TA/paas-ta-container-platform#6]
WildCard DNS 변경 처리 진행 

xip.io --> nip.io 변경

배포 Image 스크립트 및 가이드 수정필요

**Comment by jinyung0101java2** [comment]
1. Domain change complete.(xip.io --> nip.io)
2. Completed changing download url for deployment image script.

**Comment by suslmk-lee** [comment]
v1.0.5 release 반영
